---
- name: Update apt cache
  apt: update_cache=yes

- name: Assert build host kernel version
  shell: uname -r | grep "{{ initrd_kernel_version }}"
  register: host_kernel_equals_initrd_kernel
  ignore_errors: true

- name: Install initrd kernel dependencies
  apt: name=linux-image-{{ initrd_kernel_version }}
  when: "host_kernel_equals_initrd_kernel.rc != 0"

- name: Install required packages
  apt: name="{{ item.package }}={{ item.version }}"
  with_items: initrd_package_manifest

- name: Add curl hook
  copy: src=curl dest=/etc/initramfs-tools/hooks/ mode=0755

- name: Add 1_network script to local-top
  copy: src=1_network dest=/etc/initramfs-tools/scripts/local-top/ mode=0755

- name: Replace local script
  copy: src=local dest=/etc/initramfs-tools/scripts/local mode=0755

- name: Enable extra modules
  shell: "echo {{ item }} >> /etc/initramfs-tools/modules"
  with_items: 
    - squashfs
    - overlayfs
