---
- name: Build initrd image
  shell: >
    mkinitramfs -v -o 
    /boot/initrd.img-{{ initrd_kernel_version }} {{ initrd_kernel_version }}

- name: Create build output directory
  local_action: file path={{ build_artifact_path }} state=directory

- name: Move initrd image to build output directory
  local_action: >
      command mv 
      {{ build_root }}/boot/initrd.img-{{ initrd_kernel_version }}
      {{ build_artifact_path }}/initrd.img-{{ initrd_kernel_version }}

- name: Move target kernel to build output directory
  local_action: >
      command mv 
      {{ build_root }}/boot/vmlinuz-{{ initrd_kernel_version }}
      {{ build_artifact_path }}/vmlinuz-{{ initrd_kernel_version }}
