---
- name: Clean apt cache
  command: apt-get clean

- name: Remove unnecessary files
  file: path={{ item }} state=absent
  with_items:
  - /var/log/apt
  - /var/lib/apt/lists
  - /var/cache/apt/lists
  - /usr/share/doc
  - /usr/share/man
  - /usr/share/doc
  - /usr/share/man 
  - /usr/share/groff 
  - /usr/share/info 
  - /usr/share/lintian 
  - /usr/share/linda 
  - /var/cache/man
  - /var/lib/initramfs-tools 
  - /var/share/initramfs-tools 
  - /usr/lib/initramfs-tools 
  - /etc/initramfs-tools
  - /usr/share/locale
  - /usr/share/i18n/locales
