---
- name: Make read-only squashfs image directory
  file: name={{ overlayfs_lower_dir }} state=directory

- name: Mount read-only squashfs image
  shell: mount -t squashfs -o loop {{ squashfs_image_path }} {{ overlayfs_lower_dir }}

- name: Create overlay directories
  file: name={{ item }} state=directory
  with_items:
    - "{{ overlayfs_lower_dir }}"
    - "{{ overlayfs_upper_dir }}"
    - "{{ overlayfs_build_root }}"
    - "{{ overlayfs_work_dir }}"

- name: Mount overlayfs
  when: kernel_major | int == 3 and kernel_minor | int <= 16
  shell: mount -t overlayfs -o rw,upperdir={{ overlayfs_upper_dir }},lowerdir={{ overlayfs_lower_dir }} overlayfs {{ overlayfs_build_root }}

- name: Mount overlay
  when: kernel_major | int == 3 and kernel_minor | int >= 18 or kernel_major | int >= 4
  shell: mount -t overlay -o rw,upperdir={{ overlayfs_upper_dir }},lowerdir={{ overlayfs_lower_dir }},workdir={{ overlayfs_work_dir }} overlay {{ overlayfs_build_root }}

- name: Bind mount to chroot environment
  shell: mount -o bind /{{ item }} {{ overlayfs_build_root }}/{{ item }}
  with_items:
    - proc
    - dev
