---
- name: Mount read-only squashfs image
  mount: name={{ overlayfs_lower_dir }}
         src={{ squashfs_image_path }}
         fstype=squashfs 
         state=mounted
         opts="loop"

- name: Create overlay directories
  file: name={{ item }} state=directory
  with_items:
    - "{{ overlayfs_lower_dir }}"
    - "{{ overlayfs_upper_dir }}"
    - "{{ overlayfs_build_root }}"
    - "{{ overlayfs_work_dir }}"

- name: Mount overlayfs
  when: kernel_major | int == 3 and kernel_minor | int <= 16 
  mount: name={{ overlayfs_build_root }}
         src=overlayfs
         fstype=overlayfs
         opts="rw,upperdir={{ overlayfs_upper_dir }},lowerdir={{ overlayfs_lower_dir }}"
         state=mounted

- name: Mount overlay
  when: kernel_major | int == 3 and kernel_minor | int >= 18
  mount: name={{ overlayfs_build_root }}
         src=overlay
         fstype=overlay
         opts="rw,upperdir={{ overlayfs_upper_dir }},lowerdir={{ overlayfs_lower_dir }},workdir={{ overlayfs_work_dir }}"
         state=mounted
