---
- name: Unmount any existing squashfs images
  mount: name={{ overlayfs_lower_dir }}
         src={{ squashfs_image_path }}
         fstype=squashfs
         state=unmounted

- name: Unmount if directory is mounted
  mount: name={{ overlayfs_build_root }}/{{ item }}
         src=/{{ item }}
         fstype=none
         state=unmounted
  with_items:
    - proc
    - dev

- name: Unmount any existing overlayfs
  when: kernel_major | int == 3 and kernel_minor | int <= 16
  mount: name={{ overlayfs_build_root }}
         src=overlayfs
         fstype=overlayfs
         state=unmounted

- name: Unmount any existing overlay
  when: kernel_major | int == 3 and kernel_minor | int >= 18
  mount: name={{ overlayfs_build_root }}
         src=overlay
         fstype=overlay
         state=unmounted

- name: Remove any old overlay directories
  file: name={{ item }} state=absent
  with_items:
    - "{{ overlayfs_lower_dir }}"
    - "{{ overlayfs_upper_dir }}"
    - "{{ overlayfs_work_dir }}"
    - "{{ overlayfs_build_root }}"
