---
- name: Unmount any existing squashfs images
  mount: name={{ overlayfs_lower_dir }}
         src={{ squashfs_image_path }}
         fstype=squashfs 
         state=unmounted

- name: Unmount any existing overlays
  mount: name={{ overlayfs_build_root }}
         src=overlayfs
         fstype=overlayfs
         state=unmounted

- name: Remove any old overlay directories
  file: name={{ item }} state=absent
  with_items:
    - "{{ overlayfs_lower_dir }}"
    - "{{ overlayfs_upper_dir }}"
    - "{{ overlayfs_build_root }}"
