---
- name: Unmount bind mounts in build directory
  mount: name={{ build_root }}/{{ item }} 
         src=none
         fstype=none
         state=unmounted
  with_items:
    - proc
    - dev

- name: Unmount build directory
  mount: name={{ build_root }} src=tmpfs fstype=tmpfs state=unmounted

- name: Remove build directory
  file: path={{ build_root }} state=absent
