---
- name: Build and insert ami kernel driver on start
  copy: src=rc.local.hooks dest=/opt/rc.local.hooks mode=0755

- name: Copy ami flashing binary
  copy: src=ami dest=/opt

- name: Copy soc flashing binary
  copy: src=socflash dest=/opt
