---
# We need to run apt-get update because /var/cache/apt/lists gets removed
- name: Update apt cache
  command: "apt-get update"

- name: Install required packages
  apt: name="{{ item.package }}={{ item.version }}"
  with_items: discovery_overlay_package_manifest
