---
- name: add monorail user
  user: name=monorail shell=/bin/bash system=yes password='$6$zKkle4ab$4AiVrxwVv89KRiq1iM/n2cB/NjoRKCVUZkX7Gu5ws8sFDEIiANUoYx7mGqjzcyyiE9OUk0v6YqhGTjeoSPb8T0'

- name: Add localhost to /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 localhost" create=yes state=present

- name: Add monorail-micro host to /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.1.1 monorail-micro" create=yes state=present

- name: Remove existing /etc/hostname file
  file: path=/etc/hostname state=absent

- name: Add monorail-micro host to /etc/hostname
  lineinfile: dest=/etc/hostname line="monorail-micro" create=yes state=present

- name: Configure dpkg
  copy: src="{{ playbook_dir }}/files/01_nodoc" dest=/etc/dpkg/dpkg.cfg.d/01_nodoc

- name: Configure apt
  copy: src="{{ playbook_dir }}/files/apt.conf" dest=/etc/apt/apt.conf

- name: Add commonly used directories
  file: path={{ item }} state=directory mode=0777
  with_items:
    - /opt/downloads
    - /opt/uploads
    - '{{ basefs_extra_drivers_path }}'

- name: Configure apt repository lists
  lineinfile: dest={{ item.dest }} line="{{ item.line }}" create=yes state=present
  with_items: repository_lists

- name: Update apt cache
  apt: update_cache=yes

- name: Install kernel image extras
  apt: name=linux-image-extra-{{ basefs_kernel_version }}

- name: Copy pre-built kernel drivers
  shell: cp {{ item.path }}/{{ item.driver }} {{ basefs_extra_drivers_path }}/{{ item.driver }}
  with_items: basefs_extra_drivers

- name: Create build output directory
  file: path={{ build_artifact_path }} state=directory

- name: Move target kernel to build output directory
  local_action: >
      command mv 
      {{ build_root }}/boot/vmlinuz-{{ basefs_kernel_version }}
      {{ build_artifact_path }}/vmlinuz-{{ basefs_kernel_version }}

- name: Install required packages
  apt: name="{{ item.package }}={{ item.version }}"
  with_items: basefs_package_manifest

- name: Setup nodejs source for installing node v4
  shell: curl -sL https://deb.nodesource.com/setup_4.x | bash

- name: Install node v4
  apt: pkg={{ item }} state=installed
  with_items:
    - nodejs

- name: Remove extra packages in setup_4.x while installing node v4
  apt: pkg={{ item }} state=absent
  with_items:
    - lsb-release
    - dh-python
    - libpython3-stdlib
    - libpython3.4-minimal
    - libpython3.4-stdlib
    - python3
    - python3-minimal
    - python3.4
    - python3.4-minimal

- name: Add monorail to sudoers file
  lineinfile: dest=/etc/sudoers.d/11-monorail-user 
              line="monorail ALL=(ALL) NOPASSWD:ALL" 
              create=yes state=present

- name: Uninstall kernel image extras
  apt: name=linux-image-extra-{{ basefs_kernel_version }} state=absent

- name: Uninstall kernel image
  apt: name=linux-image-{{ basefs_kernel_version }} state=absent

- name: Add monorail rc.local script for task running
  copy: src="{{ playbook_dir }}/files/rc.local" dest=/etc/rc.local mode=0755

- name: Add monorail rc.local.hooks script
  copy: src=rc.local.hooks dest=/opt/rc.local.hooks mode=0755
