---
# We need to run apt-get update because /var/cache/apt/lists gets removed
- name: Update apt cache
  command: "apt-get update"

- name: Install required packages
  apt: name="{{ item.package }}={{ item.version }}"
  with_items: secure_erase_overlay_package_manifest

# Install perccli tools
- name: Copy perccli package
  copy: src="{{ playbook_dir }}/files/{{ secure_erase_overlay_perccli_package }}" dest=/opt/

- name: Install perccli tools
  command: dpkg -i /opt/{{ secure_erase_overlay_perccli_package }}

- name: Remove perccli package
  file: path=/opt/{{ secure_erase_overlay_perccli_package }} state=absent


# Install MegaRaid tools
- name: Copy storcli tool
  copy: src="{{ playbook_dir }}/files/{{ secure_erase_overlay_storcli_package }}" dest=/opt/

- name: Install storcli tools
  command: dpkg -i /opt/{{ secure_erase_overlay_storcli_package }}

- name: Remove storcli tool
  file: path=/opt/{{ secure_erase_overlay_storcli_package }} state=absent
