---
- hosts: build_local
  vars_files:
    - ../{{ config_file }}
  pre_tasks:
    - include: tasks/unmount_rootfs.yml
    - include: tasks/mount_rootfs.yml
  roles:
    - ../roles/basefs/build_rootfs

- hosts: basefs_build_chroot
  vars_files:
    - ../{{ config_file }}
  roles:
    - ../{{ provisioner }}
  post_tasks:
    - include: tasks/clean_fs.yml

- hosts: build_local
  vars_files:
    - ../{{ config_file }}
  roles:
    - ../roles/basefs/build_squashfs
  post_tasks:
    - include: tasks/unmount_rootfs.yml
