---
- hosts: build_local
  vars_files:
    - ../{{ config_file }}
  tasks:
    - include: tasks/unmount_overlay.yml
    - include: tasks/mount_overlay.yml

- hosts: overlay_build_chroot
  vars_files:
    - ../{{ config_file }}
  roles:
    - ../{{ provisioner }}
  post_tasks:
    - include: tasks/clean_fs.yml

- hosts: build_local
  vars_files:
    - ../{{ config_file }}
  roles:
    - ../roles/overlay/build_overlay_archive
  post_tasks:
    - include: tasks/unmount_overlay.yml
