---
- name: Create debian rootfs
  command: debootstrap
           --arch={{ debootstrap_arch }}
           --variant=minbase
           --include={{ ansible_dependencies }}
           --exclude={{ basefs_exclude_packages }}
           {{ debootstrap_release }}
           {{ build_root }}
           {{ debootstrap_apt_server }}

- name: Make chroot environment directory paths
  file: path={{ build_root }}/{{ item }} state=directory mode=0755
  with_items:
      - proc
      - dev

- name: Bind mount to chroot environment
  shell: mount -o bind /{{ item }} {{ build_root }}/{{ item }}
  with_items:
    - proc
    - dev
