---
- name: Create debian rootfs
  command: debootstrap 
           --arch={{ debootstrap_arch }}
           --variant=minbase 
           --include={{ ansible_dependencies }} 
           --exclude={{ basefs_exclude_packages }} 
           {{ debootstrap_release }}
           {{ build_root }}
           {{ debootstrap_apt_server }}

- name: Bind mount to chroot environment
  mount: name={{ build_root }}/{{ item }} 
         src=/{{ item }}
         fstype=none
         opts="bind"
         state=mounted
  with_items:
    - proc
    - dev
