---
- name: Install Ubuntu build dependencies
  apt: name={{ item }} state=present
  with_items:
    - debootstrap
    - squashfs-tools
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
